import './style.css';
import { AssetViewer } from './asset-viewer.js';
import { createDeck } from './deck/deck.js';

const app = document.getElementById('app');
let blender = [];
let evals = [];
let concepts = {};
let viewer = null;
let deck = null;

const BASE = import.meta.env.BASE_URL;

const PIPELINE = [
  ['01', 'Prompt', 'A written brief: the object or world, its parts, its purpose.'],
  ['02', 'Geometry', '3D models generated per part — meshes, materials, textures.'],
  ['03', 'Articulation', 'Joints, hinges, sliders and kinematic chains, rigged and animated.'],
  ['04', 'Composition', 'Terrain, layout, placement and density composed into full scenes.'],
  ['05', 'Atmosphere', 'Lighting, sky, fog and post-processing tuned to the concept.'],
  ['06', 'Engine-ready', 'Runnable Blender and Godot files — simulation targets, not renders.'],
];

async function boot() {
  const [b, e, c] = await Promise.all([
    fetch(BASE + 'data/blender.json').then((r) => (r.ok ? r.json() : [])),
    fetch(BASE + 'data/evals.json').then((r) => (r.ok ? r.json() : [])),
    fetch(BASE + 'data/concepts.json').then((r) => (r.ok ? r.json() : {})).catch(() => ({})),
  ]);
  blender = [...b, ...e];
  evals = e;
  concepts = c;
  route();
  window.addEventListener('hashchange', route);
}

// Hash anchors that belong to the classic gallery landing.
const GALLERY_ANCHORS = ['gallery', 'play', 'objects', 'environments', 'blender-worlds', 'pipeline'];

function route() {
  const assetMatch = /^#\/asset\/([\w-]+)/.exec(location.hash);
  if (viewer) {
    viewer.dispose();
    viewer = null;
  }
  if (deck) {
    deck.destroy();
    deck = null;
  }
  const anchor = location.hash.replace(/^#/, '');
  if (assetMatch && blender.some((a) => a.slug === assetMatch[1])) {
    renderAssetViewer(assetMatch[1]);
  } else if (GALLERY_ANCHORS.includes(anchor)) {
    renderLanding();
    if (anchor === 'gallery') window.scrollTo(0, 0);
    else document.getElementById(anchor)?.scrollIntoView();
  } else {
    renderDeck();
  }
}

// ------------------------------------------------------------- deck (default landing)

function renderDeck() {
  document.title = 'Generated Worlds — AI 3D Content Generation';
  app.innerHTML = '';
  window.scrollTo(0, 0);
  deck = createDeck(app, { blender, evals, concepts });
}

// ------------------------------------------------------------- landing

function renderLanding() {
  document.title = 'Generated Worlds — AI 3D Content Generation';
  const objects = blender.filter((b) => b.group === 'objects');
  const envs = blender.filter((b) => b.group === 'environments');
  const worlds = blender.filter((b) => b.group === 'worlds');

  // Live hero pick: an animated mechanism that shows off articulation.
  const heroItem =
    blender.find((b) => b.group === 'objects' && b.animated) ??
    blender.find((b) => b.animated) ??
    null;

  app.innerHTML = `
    <div class="landing">
      <nav class="topnav">
        <div class="brand">GENERATED<span>WORLDS</span></div>
        <div class="links">
          <a href="#deck" title="back to the card deck">◈ Deck</a>
          <a href="#play">Playable Demo</a>
          <a href="#objects">Objects</a>
          <a href="#environments">Environments</a>
          <a href="#blender-worlds">Worlds</a>
          <a href="#pipeline">Pipeline</a>
        </div>
      </nav>

      <section class="hero hero-split">
        <div class="hero-copy">
          <h1>Prompts in. <em>Interactive 3D Worlds</em> out.</h1>
          <p class="lede">
            Everything on this page was generated by an AI pipeline from a written
            brief — articulated objects with real kinematics, full simulation
            environments, and entire generated worlds. Not concept renders:
            engine-ready files with joints that move and doors that open.
            Every item is live — drag it. There's even a complete game you can <a class="lede-link" href="#play">play</a>.
          </p>
          <div class="hero-stats">
            <div class="stat"><div class="num">${objects.length}</div><div class="label">Articulated objects</div></div>
            <div class="stat"><div class="num">${envs.length}</div><div class="label">Environments</div></div>
            <div class="stat"><div class="num">${worlds.length}</div><div class="label">Blender worlds</div></div>
            <div class="stat"><div class="num">1</div><div class="label">Playable demo</div></div>
          </div>
        </div>
        <div class="hero-stage">
          <div class="hero-canvas" id="hero-canvas"></div>
          <div class="hero-caption">${heroItem ? escapeHtml(heroItem.slug) + '.blend' : ''} — generated from one sentence, articulated &amp; live</div>
        </div>
      </section>

      <section class="collection" id="play">
        <div class="gallery-head">
          <div>
            <h2>Playable Demo — Ghosts in the Dataset</h2>
            <p class="section-sub">Not a video. A complete AI-generated game — cyberpunk street, arcade cabinets with working mini-games, NPCs, a claw machine — running in your browser via a Godot web build.</p>
          </div>
          <div class="hint">WASD to move · mouse to look · E to interact</div>
        </div>
        <div class="playable-wrap">
          <a class="playable-banner" href="${BASE}play/ghost/index.html" target="_blank" rel="noopener">
            <img class="playable-shot" src="${BASE}play/ghost/promo/street.webp" alt="Ghosts in the Dataset — cyberpunk street" loading="lazy" />
            <div class="playable-overlay">
              <div class="playable-meta">
                <div class="playable-kicker">GODOT 4 · WEB BUILD · RUNS AT 60 FPS</div>
                <h3>Ghosts in the Dataset</h3>
                <p>A third-person cyberpunk world: sakura petals over a tron-grid park, neon noodle bar, playable Pong &amp; Snake cabinets, procedural audio, dwell-scan interactions. Every asset generated by AI.</p>
              </div>
              <span class="playable-cta">▶ Play in browser</span>
            </div>
          </a>
          <div class="playable-side">
            <img src="${BASE}play/ghost/promo/title.webp" alt="Ghosts in the Dataset title screen" loading="lazy" />
            <div class="playable-note">
              <div class="prompt-label">WHAT THIS PROVES</div>
              <p>Generated content isn't just visual — it ships. This demo packs AI-generated buildings, characters and interactables into a playable build with game logic, physics and UI. ~150 MB, loads in under a minute.</p>
            </div>
          </div>
        </div>
      </section>

      <section class="collection" id="objects">
        <div class="gallery-head">
          <div>
            <h2>Articulated Objects</h2>
            <p class="section-sub">Generated with functional joints — hinges, sliders, kinematic chains — and motion baked in. Click one to play its mechanism.</p>
          </div>
          <div class="hint">${objects.length} objects · click to enter studio</div>
        </div>
        <div class="grid grid-objects">
          ${objects.map(assetCardHtml).join('')}
        </div>
      </section>

      <section class="collection" id="environments">
        <div class="gallery-head">
          <div>
            <h2>Greybox Scenes</h2>
            <p class="section-sub">Greybox scenes for robotics, digital twins and synthetic data — warehouses, production lines, hospitals, resorts — generated as single Blender files.</p>
          </div>
          <div class="hint">${envs.length} environments · rendered live</div>
        </div>
        <div class="grid grid-envs">
          ${envs.map(assetCardHtml).join('')}
        </div>
      </section>

      <section class="collection" id="blender-worlds">
        <div class="gallery-head">
          <div>
            <h2>Generated Worlds — Blender</h2>
            <p class="section-sub">Entire outdoor worlds from one-sentence prompts — terrain, architecture, props and lighting reconstructed as a single Blender scene.</p>
          </div>
          <div class="hint">${worlds.length} worlds · rendered live</div>
        </div>
        <div class="grid grid-envs">
          ${worlds.map(assetCardHtml).join('')}
        </div>
      </section>

      <section class="pipeline" id="pipeline">
        <div class="gallery-head"><h2>One pipeline, prompt to engine</h2></div>
        <div class="pipeline-row">
          ${PIPELINE.map(
            ([n, t, d]) => `
            <div class="pipeline-step">
              <div class="step-n">${n}</div>
              <div class="step-t">${t}</div>
              <div class="step-d">${d}</div>
            </div>`,
          ).join('')}
        </div>
      </section>

      <footer>
        <div>Generated Worlds — AI 3D content generation showcase</div>
        <div>Blender · Godot 4 · rendered on the web with three.js</div>
      </footer>
    </div>
  `;

  // Live hero: an animated mechanism playing on a transparent stage.
  if (heroItem) {
    const el = document.getElementById('hero-canvas');
    viewer = new AssetViewer(el, {});
    viewer.load(heroItem.url, { loopPingPong: !!heroItem.loopPingPong });
  }
}

function assetCardHtml(a) {
  const prompt = a.prompt ? escapeHtml(a.prompt) : '';
  return `
    <a class="card card-asset" href="#/asset/${a.slug}">
      <img class="thumb" src="${BASE}${a.thumbnail}" alt="${escapeHtml(a.title)}" loading="lazy"
           onerror="this.outerHTML='<div class=&quot;thumb placeholder&quot;>rendering…</div>'" />
      ${a.animated ? '<span class="motion-badge">▶ motion</span>' : ''}
      <span class="enter">open studio →</span>
      <div class="body">
        <div class="scene-id">${escapeHtml(a.badge.toUpperCase())} · ${fmtPolys(a.polys)} tris</div>
        <h3>${escapeHtml(a.title)}</h3>
        ${prompt ? `<div class="desc">“${prompt}”</div>` : ''}
      </div>
    </a>
  `;
}

// ------------------------------------------------------------- blender asset viewer

function renderAssetViewer(slug) {
  const item = blender.find((a) => a.slug === slug);
  const siblings = blender.filter((a) => a.group === item.group);
  const idx = siblings.indexOf(item);
  const prev = siblings[(idx - 1 + siblings.length) % siblings.length];
  const next = siblings[(idx + 1) % siblings.length];
  const isEnv = item.group === 'environments' || item.group === 'worlds';
  const conceptUrl = concepts[item.slug] ? BASE + concepts[item.slug] : null;
  document.title = `${item.title} — Generated Worlds`;

  app.innerHTML = `
    <div class="viewer">
      <div class="viewer-canvas" style="position:absolute;inset:0"></div>
      <div class="loader">
        <div class="loader-inner">
          <div class="scene-name">${escapeHtml(item.title)}</div>
          <div class="status">loading model…</div>
          <div class="progress"><div class="bar indeterminate"></div></div>
        </div>
      </div>
      <div class="viewer-hud">
        <div class="hud-top">
          <div class="left">
            <a class="back-btn" href="#${item.group === 'worlds' ? 'blender-worlds' : isEnv ? 'environments' : 'objects'}">← back</a>
            <div class="hud-title">
              <h2>${escapeHtml(item.title)}</h2>
              <div class="sub">${escapeHtml(item.badge.toUpperCase())} · ${fmtPolys(item.polys)} TRIS · ${item.sizeKB > 1024 ? (item.sizeKB / 1024).toFixed(1) + ' MB' : item.sizeKB + ' KB'} · BLENDER SOURCE</div>
            </div>
          </div>
          <div class="nav">
            <a class="nav-btn" href="#/asset/${prev.slug}" title="${escapeHtml(prev.title)}">‹</a>
            <a class="nav-btn" href="#/asset/${next.slug}" title="${escapeHtml(next.title)}">›</a>
          </div>
        </div>
        <div class="hud-bottom hud-bottom-asset">
          <div class="hud-left-stack">
            ${conceptUrl ? `
            <div class="concept-panel">
              <div class="prompt-label">CONCEPT REFERENCE</div>
              <img class="concept-thumb" src="${conceptUrl}" alt="Concept art for ${escapeHtml(item.title)}" title="click to enlarge" />
            </div>` : ''}
            ${item.prompt ? `
            <div class="prompt-panel">
              <div class="prompt-label">GENERATION PROMPT</div>
              <div class="prompt-text">“${escapeHtml(item.prompt)}”</div>
            </div>` : ''}
          </div>
          <div class="anim-controls" hidden>
            <button class="play-btn" title="play/pause">❚❚</button>
            <input class="scrub" type="range" min="0" max="1000" value="0" />
            <span class="anim-time">0.0s</span>
          </div>
        </div>
      </div>
    </div>
  `;

  const container = app.querySelector('.viewer-canvas');
  const loaderEl = app.querySelector('.loader');
  const controls = app.querySelector('.anim-controls');
  const playBtn = app.querySelector('.play-btn');
  const scrub = app.querySelector('.scrub');
  const timeEl = app.querySelector('.anim-time');
  let scrubbing = false;

  viewer = new AssetViewer(container, {
    onReady: ({ animated, duration }) => {
      loaderEl.classList.add('done');
      window.__SCENE_READY = true;
      if (animated && duration > 0.5) {
        controls.hidden = false;
      }
    },
    onError: () => {
      loaderEl.innerHTML = `<div class="viewer-error">Failed to load this asset.<br/><a href="#/" style="color:var(--accent)">back to gallery</a></div>`;
    },
    onTime: (t, dur) => {
      if (scrubbing) return;
      scrub.value = String(Math.round((t / Math.max(dur, 1e-6)) * 1000));
      timeEl.textContent = t.toFixed(1) + 's';
    },
  });
  window.__SCENE_READY = false;
  window.__VIEWER = viewer;
  // Capture scripts pass ?thumb=<zoom> for tighter thumbnail framing, or
  // ?fp=x,y,z,yaw[,pitch[,fov]] for first-person ground-level thumbnails;
  // never set during normal browsing, so visitors see the default framing.
  const search = new URLSearchParams(location.search);
  const thumbParam = search.get('thumb');
  const fpParam = search.get('fp');
  const fpCamera = isEnv && fpParam ? parseFpParam(fpParam) : null;
  viewer.load(item.url, {
    environment: isEnv,
    // First-person shots keep ceilings/roofs: an interior should read as a
    // real room, not a dollhouse.
    hideCeilings: !fpCamera && (item.collection === 'interiors' || item.collection === 'scenes'),
    skyUrl: item.sky ? BASE + item.sky : null,
    loopPingPong: !!item.loopPingPong,
    thumbFrame: isEnv && thumbParam ? parseFloat(thumbParam) || 1 : 0,
    fpCamera,
    lightBoost: item.lightBoost || 1,
  });

  playBtn.addEventListener('click', () => {
    viewer.setPlaying(!viewer.playing);
    playBtn.textContent = viewer.playing ? '❚❚' : '▶';
  });
  scrub.addEventListener('pointerdown', () => (scrubbing = true));
  scrub.addEventListener('pointerup', () => (scrubbing = false));
  scrub.addEventListener('input', () => {
    const t = (Number(scrub.value) / 1000) * viewer.duration;
    viewer.seek(t);
    timeEl.textContent = t.toFixed(1) + 's';
  });

  const conceptThumb = app.querySelector('.concept-thumb');
  if (conceptThumb) {
    conceptThumb.addEventListener('click', () => openConceptLightbox(conceptUrl, item.title));
  }
}

function openConceptLightbox(url, title) {
  const overlay = document.createElement('div');
  overlay.className = 'concept-lightbox';
  overlay.innerHTML = `
    <img src="${url}" alt="Concept art for ${escapeHtml(title)}" />
    <div class="concept-lightbox-caption">CONCEPT REFERENCE — ${escapeHtml(title.toUpperCase())} · CLICK OR ESC TO CLOSE</div>
  `;
  const close = () => {
    overlay.remove();
    document.removeEventListener('keydown', onKey);
  };
  const onKey = (e) => {
    if (e.key === 'Escape') close();
  };
  overlay.addEventListener('click', close);
  document.addEventListener('keydown', onKey);
  document.body.appendChild(overlay);
}

// ?fp=x,y,z,yaw[,pitch[,fov]] — first-person capture camera, in the GLB's
// original (pre-centering) coordinates; yaw/pitch in degrees, yaw 0 = -Z.
function parseFpParam(raw) {
  const parts = raw.split(',').map(Number);
  if (parts.length < 3 || !parts.slice(0, 3).every(Number.isFinite)) return null;
  const [x, y, z, yaw = 0, pitch = 0, fov = 62] = parts;
  return { position: [x, y, z], yaw: yaw || 0, pitch: pitch || 0, fov: fov || 62 };
}

function fmtPolys(n) {
  if (n >= 1e6) return (n / 1e6).toFixed(1) + 'M';
  if (n >= 1e3) return (n / 1e3).toFixed(0) + 'K';
  return String(n);
}

function escapeHtml(s) {
  return s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
}

boot();
